### ISSUE TITLE
Scope NameError - DriveV3 or TasksV1?

### ISSUE THREAD

**Issue by matthew-t-smith** [gsuitedevs/ruby-samples#13]
## Expected Behavior
`SCOPE` constant to initialize

## Actual Behavior
`NameError` - uninitialized constant Google::Apis::DriveV3

## Specifications

- Ruby version (`ruby -v`): 2.5.1
- OS (Mac/Linux/Windows): macOS 10.13.6

## Question
In the `SCOPE` constant declaration, it calls for the `Google::Apis::DriveV3::AUTH_TASKS_READONLY`

Is this meant to be `Google::Apis::TasksV1::AUTH_TASKS_READONLY`? I swapped and was able to get past the NameError.

**Comment by erickoledadevrel** [comment]
Good catch! Fixed the error.
