### ISSUE TITLE
error on puts response

### ISSUE THREAD

**Issue by adolfoyanes** [gsuitedevs/ruby-samples#14]
## Expected Behavior

puts row[0] and row[4]
## Actual Behavior

NoMethodError (undefined method `each_value' for #<Google::Apis::SheetsV4::ValueRange:0x00007ff91294f008>)

## Steps to Reproduce the Problem

1. Run the sample file
1. see the error on console
1.

## Specifications

- Ruby version (`ruby -v`)
2.5.1p57
- OS (Mac/Linux/Windows)
mac 10.13.16

**Comment by jksk** [comment]
Change the line
`response.each_value do |row|`
to 
`response.values.each do |row|`
