### ISSUE TITLE
Load Error sheets_v4

### ISSUE THREAD

**Issue by PurityMaina** [gsuitedevs/ruby-samples#15]
## Expected Behavior

Read sheets
## Actual Behavior
require': cannot load such file -- google/apis/sheet_v4 (LoadError)

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Ruby version (`ruby -v`)
- OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
Can you post what the solution was, in case other folks run into this issue?
