### ISSUE TITLE
Remove the begin-rescue block from quickstart

### ISSUE THREAD

**Issue by kolbykskk** [gsuitedevs/ruby-samples#16]
## Expected Behavior
Expected the quickstart to authenticate me after visiting the link and pasting in the authorization code.

## Actual Behavior
It got caught in the begin-rescue block and threw a Google::Apis::ClientError error.

## Steps to Reproduce the Problem

1. run `ruby quickstart.rb`
2. click the link and authorize Google account
3. Copy/paste the authorization code into the terminal
4. Get the Google::Apis::ClientError error with the message "The request is invalid and should not be retried without modification."

## Specifications

- Ruby version 2.4.4
- OS Linux Ubuntu 18.04

I simply removed the begin-rescue block from the quickstart.rb code altogether and it then gave me a much more helpful error that I was able to fix. 

That error was this: "User has not enabled the Apps Script API. Enable it by visiting https://script.google.com/home/usersettings then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systemsand retry."

Thanks!

**Comment by erickoledadevrel** [comment]
Thanks for raising this issue, certainly doesn't help to suppress that error, and our other quickstarts aren't doing this.
