### ISSUE TITLE
Gmail quickstart.rb Runtime error

### ISSUE THREAD

**Issue by jball5** [gsuitedevs/ruby-samples#17]
## Expected Behavior
puts labels

## Actual Behavior
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/googleauth-0.6.7/lib/googleauth/client_id.rb:99:in `from_hash': Expected top level property 'installed' or 'web' to be present. (RuntimeError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/googleauth-0.6.7/lib/googleauth/client_id.rb:85:in `block in from_file'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/googleauth-0.6.7/lib/googleauth/client_id.rb:82:in `open'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/googleauth-0.6.7/lib/googleauth/client_id.rb:82:in `from_file'
        from quickstart.rb:22:in `authorize'
        from quickstart.rb:42:in `<main>'

## Steps to Reproduce the Problem

1. Followed the steps in the Gmail API guide.
1.
1.

## Specifications

- Ruby version (`ruby -v`)
- OS (Mac/Linux/Windows)
ruby 2.4.4p296 Windows

**Comment by erickoledadevrel** [comment]
The error seems to indicate that the contents in `credentials.json` aren't what was expected. Can you post a sanitized version of the content of that file? Can you confirm that the credentials file you downloaded was saved to the correct location?

**Comment by jball5** [comment]
I created an OAuth Client ID credential instead of a service application credential and everything appears to be functional. Thanks!
