### ISSUE TITLE
Google calendar api 

### ISSUE THREAD

**Issue by 0limpi0** [gsuitedevs/ruby-samples#22]
## Expected Behavior
The first time you run the sample, it will prompt you to authorize access:

    The sample will attempt to open a new window or tab in your default browser. If this fails, copy the URL from the console and manually open it in your browser.

    If you are not already logged into your Google account, you will be prompted to log in. If you are logged into multiple Google accounts, you will be asked to select one account to use for the authorization.
    Click the Accept button.
    The sample will proceed automatically, and you may close the window/tab.

## Actual Behavior
C:\Users\WEBSITE\Desktop\gcapi>ruby quickstart.rb
Traceback (most recent call last):
        2: from quickstart.rb:1:in `<main>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- google/apis/calendar_v3 (LoadError)

## Steps to Reproduce the Problem

1. Tried to check if the code is wrong
2. Checked if the gem installed well

## Specifications

- Ruby version (`ruby -v`)
- OS (Mac/Linux/Windows)

**Comment by sqrrrl** [comment]
Can you try uninstalling the gem then reinstalling without the version specifier (just install latest). Looks like the instructions for the quickstart incorrectly point to an old version while the code assumes a newer one.

Let me know if that resolves the issue and I'll have the docs updated.

**Comment by sqrrrl** [comment]
Went ahead and fixed the docs. Marking this as fixed, but feel free to re-open if you're still having the issue after installing more recent versions of the gem.
