### ISSUE TITLE
PeoploeV3 does not exist, only PeopleV1

### ISSUE THREAD

**Issue by nmingotti** [gsuitedevs/ruby-samples#8]
Following instructions in : https://developers.google.com/people/quickstart/ruby

Here is the error i get:

    test-google-poeple-api.rb:15:in `<main>': uninitialized constant Google::Apis::PeopleV3 (NameError)

Then tabbing in Pry I get only Google::Apis::PeopleV1 
and not Google::Apis::PeopleV3

**Comment by erickoledadevrel** [comment]
Fixed! Thanks for reporting it.
