### ISSUE TITLE
Another fix and a suggestion for output 

### ISSUE THREAD

**Issue by nmingotti** [gsuitedevs/ruby-samples#9]
I don't know much about Git, i will tell you here what i found,

again in reference to : https://developers.google.com/people/quickstart/ruby

to have the code working I subsitued line
`service = Google::Apis::PeopleV1::PeopleService.new`
with :
`service = Google::Apis::PeopleV1::PeopleServiceService.new`

Then, to have the the code actually print something i would close with someting like this:

```rb
    # Fetch the next 600 events for the user
    response = service.list_person_connections(
      'people/me',
      page_size: 600,
      person_fields: ["names", "phoneNumbers", "emailAddresses"]
      # person_fields: 'names,emailAddresses,phoneNumbers'
    )
    
    # print first name, phone and email for each connection
    response.connections.each do |con|
      name = "???"; phone = "???"; mail = "???";
      begin name = con.names.first.display_name;  rescue;  end
      begin phone = con.phone_numbers.first.canonical_form; rescue; end 
      begin mail = con.email_addresses.first.value; rescue; end 
      # don't print connections with all undefined values 
      next if ((name == phone)  && (phone == mail))
      puts "#{name} === #{phone} == #{mail}"  
    end
```

**Comment by grant** [comment]
Thank you for reporting!
I've fixed `PeopleServiceService` in https://github.com/gsuitedevs/ruby-samples/commit/2775c0abe2320ac4f53a5aaa349309571d52f180.

https://developers.google.com/people/quickstart/ruby

For the alternative output, we must keep all the languages the same, but other users can search here to find your sample.
